name: slide_countdown
description: A Flutter package to create easy slide animation countdown / countup timer.
version: 1.6.1
repository: https://github.com/farhanfadila1717/slide_countdown
issue_tracker: https://github.com/farhanfadila1717/slide_countdown/issues
maintainer: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_duration: ">=4.2.2 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

screenshots:
  - description: "Examples of the SlideCountdown."
    path: ss.png

topics:
  - timer
  - countdown
  - countup
  - animation
